version: '3.8'

services:

  pgsql:
    image: postgres:16
    container_name: teba-pgsql
    environment:
      POSTGRES_DB: tebatravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - teba_pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teba-api
    depends_on:
      pgsql:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=pgsql;Port=5432;Database=tebatravel;Username=postgres;Password=postgres

volumes:
  teba_pgdata: